name: Build Docker Image for Next.js React App

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  prep-environment:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
      
      - name: Show available architectures via QEMU
        run: echo ${AVAILABLE}
        env:
          AVAILABLE: ${{ steps.qemu.outputs.platforms }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Build the Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./mail-aliases/
          file: ./mail-aliases/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: dev-latest